# Generated by Django 2.2.3 on 2019-07-15 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='activation_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='activation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 23, 16, 33, 749623)),
        ),
    ]
